# Generated by Django 2.0.7 on 2018-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='seq',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
